### ISSUE TITLE
error when running slideshow commands

### ISSUE THREAD

**Issue by greggles** [slideshow-s9/slideshow-models#18]
I'm having some trouble. This same error happens regardless of what command I run. Any thoughts?

```
tacotown:~ greggles$ slideshow install deck.js
/usr/local/Cellar/ruby/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- active_record (LoadError)
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/props-1.1.1/lib/props/db.rb:7:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/textutils-0.9.4/lib/textutils.rb:19:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/markdown-1.1.1/lib/markdown.rb:28:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/slideshow-2.3.0/lib/slideshow.rb:28:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/slideshow-2.3.0/bin/slideshow:3:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.1.1/bin/slideshow:23:in `load'
    from /usr/local/Cellar/ruby/2.1.1/bin/slideshow:23:in `<main>'
tacotown:~ greggles$ gem -v
2.2.2
tacotown:~ greggles$ which gem
/usr/local/bin/gem
tacotown:~ greggles$ ls -l /usr/local/bin/gem
lrwxr-xr-x  1 greggles  admin  28 May 30 08:28 /usr/local/bin/gem -> ../Cellar/ruby/2.1.2/bin/gem
tacotown:~ greggles$
```

**Comment by geraldb** [comment]
Thanks for trying slideshow. Please post installation issues to the [mailing list/forum](http://groups.google.com/group/wwwmake). Cheers.
